user:
  name: 
    maximum: 50
  email:
    maximum: 120
  address:
    maximum: 120
  password:
    minimum: 6
  size_image: 50  
comment:
  description:
    maximum: 255
ratings:
  point: 1..5
category:
  name:
    maximum: 100
page:
  per: 10
  product: 12
picture:
  size: 5
  size_fit: 400
  type: "image/jpeg,image/gif,image/png"
  default: "default.png"
products:
  index:
    per_page: 16
ramdom:
  length: "0...10"
  char: "a..z"
  num: 26
rules_new_product: 7   
time: 2
